spring:
  application:
    name: catalog
  datasource:
    url: jdbc:postgresql://localhost:5432/Catalog
    username: postgres
    password: 99ronore
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  mvc:
    servlet:
      path: /catalog
server:
  port: 6668
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:9999/myeureka/eureka}
    initial-instance-info-replication-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    preferIpAddress: true
    ip-address: 127.0.0.1