spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Orders
    username: postgres
    password: 99ronore
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
