server:
  port: 6666
catalog:
  name: catalog
inventory:
  name: inventory
customer-management:
  name: customer-management
spring:
  application:
    name: processor
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:9999/myeureka/eureka}
  instance:
    lease-renewal-interval-in-seconds: 5
    preferIpAddress: true
    ip-address: 127.0.0.1