server:
  port: 9999
  servlet:
    context-path: /myeureka

eureka:
  server:
    response-cache-update-interval-ms: 1000
    eviction-interval-timer-in-ms: 100
    enable-self-preservation: true
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1